.TH "/home/thierry/Sources/Opengl/Lesson03/src/logger.h" 3 "Thu Mar 23 2023" "Version 2.1.0" "Lesson03 (from NeHe)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/thierry/Sources/Opengl/Lesson03/src/logger.h \- Header de l'ajout de fonction de 'logging' (traces dans un fichier texte log\&.txt) uniquement en mode Debug et avec des niveaux de tracing définis dans une variable d'environnement (LEVEL)  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBlog_print\fP (char *filename, int line, char *fmt,\&.\&.\&.)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Header de l'ajout de fonction de 'logging' (traces dans un fichier texte log\&.txt) uniquement en mode Debug et avec des niveaux de tracing définis dans une variable d'environnement (LEVEL) 

Comments manageable by Doxygen
.PP
Modified by Thierry DECHAIZE
.PP
Date : 2023/03/05
.PP
\fBAuthor\fP
.RS 4
Thierry Dechaize 
.RE
.PP
\fBVersion\fP
.RS 4
2\&.0\&.1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
5 mars 2023
.RE
.PP
Il s'agit de pouvoir partager les deux fonctions utiles de cet utilitaire\&. 
.SH "Function Documentation"
.PP 
.SS "void log_print (char * filename, int line, char * fmt,  \&.\&.\&.)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Lesson03 (from NeHe) from the source code\&.
